-- =============================================================================
-- Launch announcement, sent from the database.
--
-- GENERATED by scripts/gen-announce-sql.mjs from the same email module the Edge
-- Function uses. Do not hand-edit the copy below — regenerate it, or the two
-- senders drift apart.
--
-- Needs: pg_net (Database → Extensions) and the Resend key in Vault.
-- =============================================================================

create extension if not exists pg_net;

-- --- The key, stored once -----------------------------------------------------
-- Replace re_xxx with your Resend API key and run this line ONCE. It is stored
-- encrypted; nothing below ever prints it.
--
--   select vault.create_secret('re_xxx', 'resend_api_key');
--
-- Already stored one and want to change it:
--   select vault.update_secret(id, 're_new') from vault.secrets where name = 'resend_api_key';

-- --- The sender ---------------------------------------------------------------

create or replace function public.announce_launch(
  p_limit    int  default 50,
  p_test_to  text default null,
  p_from     text default 'Pocket Athlete <hello@pocketathlete.com>'
)
returns table (emailed int, remaining int, note text)
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_key   text;
  v_html  text := $mail$<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Pocket Athlete is live — your spot is ready 🔥</title></head>
<body style="margin:0;padding:0;background:#0b0f0d;">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;">Your position. Your plan. Your numbers. It's open.</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#0b0f0d;padding:24px 12px;">
<tr><td align="center">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#121714;border-radius:20px;padding:32px 26px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">

  <tr><td style="font-size:30px;line-height:1.15;font-weight:800;color:#f1f5f3;padding-bottom:6px;">
    It's live. 🔥
  </td></tr>

  <tr><td style="font-size:16px;line-height:1.6;color:#9fb0a8;padding-bottom:22px;">
    You put your name down for Pocket Athlete. It's open — go and use it.
  </td></tr>

  <tr><td style="padding-bottom:22px;">
    <a href="@@CTA@@" style="display:inline-block;background:#e3b53f;color:#0b0f0d;font-size:17px;font-weight:800;text-decoration:none;padding:15px 30px;border-radius:999px;">
      Open Pocket Athlete →
    </a>
  </td></tr>

  <tr><td style="padding-bottom:18px;">
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr>
      <td width="34" valign="top" style="font-size:20px;line-height:1.3;">🎯</td>
      <td valign="top">
        <div style="font-size:15px;font-weight:700;color:#f1f5f3;padding-bottom:3px;">Built for your position</div>
        <div style="font-size:14px;line-height:1.55;color:#9fb0a8;">A prop and a winger get different sessions. 33 positions across 6 sports — not one generic plan with your sport's name on it.</div>
      </td>
    </tr></table>
  </td></tr>
  <tr><td style="padding-bottom:18px;">
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr>
      <td width="34" valign="top" style="font-size:20px;line-height:1.3;">🎥</td>
      <td valign="top">
        <div style="font-size:15px;font-weight:700;color:#f1f5f3;padding-bottom:3px;">Film a rep, have it read</div>
        <div style="font-size:14px;line-height:1.55;color:#9fb0a8;">Depth, tempo, bar path, the knee collapsing on rep 8 — with the drills to fix what it finds. The analysis runs on your own phone.</div>
      </td>
    </tr></table>
  </td></tr>
  <tr><td style="padding-bottom:18px;">
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr>
      <td width="34" valign="top" style="font-size:20px;line-height:1.3;">🍽️</td>
      <td valign="top">
        <div style="font-size:15px;font-weight:700;color:#f1f5f3;padding-bottom:3px;">Food that adds up</div>
        <div style="font-size:14px;line-height:1.55;color:#9fb0a8;">Calorie and macro targets, meal plans built round your training, and a shopping list with prices on it.</div>
      </td>
    </tr></table>
  </td></tr>
  <tr><td style="padding-bottom:18px;">
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr>
      <td width="34" valign="top" style="font-size:20px;line-height:1.3;">🏆</td>
      <td valign="top">
        <div style="font-size:15px;font-weight:700;color:#f1f5f3;padding-bottom:3px;">Something to chase</div>
        <div style="font-size:14px;line-height:1.55;color:#9fb0a8;">136 challenges, 62 badges, and a rank ladder that runs Iron to Legend. It tracks your load too — so when you need to back off, it says so, and pays you for the rest day.</div>
      </td>
    </tr></table>
  </td></tr>

  <tr><td style="padding-top:8px;padding-bottom:26px;font-size:16px;line-height:1.6;color:#9fb0a8;">
    Free to start. No card needed.
  </td></tr>

  <tr><td style="border-top:1px solid rgba(255,255,255,0.08);padding-top:18px;font-size:12px;line-height:1.6;color:#6b7a73;">
    You're getting this because you joined the Pocket Athlete waitlist.<br>
    <a href="@@UNSUB@@" style="color:#9fb0a8;text-decoration:underline;">Unsubscribe</a> — one click, no questions.
  </td></tr>

</table>
</td></tr></table>
</body></html>$mail$;
  v_text  text := $mail$It's live.

You put your name down for Pocket Athlete. It's open — go and use it.

What you get:

- Training built for your POSITION, not just your sport. A prop and a winger
  get different sessions. 33 positions across 6 sports.
- Film a rep and have it read frame by frame — depth, tempo, bar path, the
  knee collapsing on rep 8 — with the drills to fix what it finds. The
  analysis runs on your own phone.
- Nutrition that adds up: targets, meal plans, a shopping list with prices.
- 136 challenges, 62 badges and a rank ladder from Iron to Legend.

And it watches your training load, so when you need to back off it says so —
and pays you for the rest day rather than only for the grind.

Start here: @@CTA@@

Free to start. No card needed.

—
You're getting this because you joined the Pocket Athlete waitlist.
Unsubscribe: @@UNSUB@@$mail$;
  v_subj  text := $mail$Pocket Athlete is live — your spot is ready 🔥$mail$;
  v_app   text := $mail$https://pocketathlete.com$mail$;
  r       record;
  v_cta   text;
  v_unsub text;
  v_sent  int := 0;
  v_left  int;
begin
  if not public.is_admin() then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  select decrypted_secret into v_key from vault.decrypted_secrets where name = 'resend_api_key';
  if v_key is null then
    raise exception 'No Resend key in Vault. Run: select vault.create_secret(''re_xxx'', ''resend_api_key'');';
  end if;

  -- ONE ADDRESS, TOUCHING NOTHING. Returns before the real query so a test can
  -- be fired as often as you like while tweaking the copy — if it consumed a
  -- place in the batch, checking the email would remove people from the send it
  -- was checking.
  if p_test_to is not null then
    v_cta   := v_app || '/';
    v_unsub := v_app || '/unsubscribe?t=' || gen_random_uuid()::text;
    perform net.http_post(
      url     := 'https://api.resend.com/emails',
      headers := jsonb_build_object('Content-Type', 'application/json',
                                    'Authorization', 'Bearer ' || v_key),
      body    := jsonb_build_object(
        'from', p_from, 'to', p_test_to,
        'subject', '[TEST] ' || v_subj,
        'html', replace(replace(v_html, '@@CTA@@', v_cta), '@@UNSUB@@', v_unsub),
        'text', replace(replace(v_text, '@@CTA@@', v_cta), '@@UNSUB@@', v_unsub))
    );
    return query select 0, 0,
      'Test queued to ' || p_test_to || '. Nobody on the waitlist was emailed, marked or skipped.';
    return;
  end if;

  -- Never anyone who left, never anyone already told. The stamp is what makes
  -- pressing this twice safe, and it is why it can be run in batches.
  for r in
    select w.id, w.email, w.unsub_token,
           coalesce(nullif(trim(w.referral_code), ''), nullif(trim(w.source), '')) as ref
      from public.waitlist w
     where w.unsubscribed_at is null
       and w.launch_emailed_at is null
     order by w.created_at
     limit greatest(1, p_limit)
  loop
    -- The affiliate code that brought them in. Attribution does not depend on
    -- it — 0057 binds the email to its referrer permanently and signup reads
    -- that ledger — but it covers someone signing up with a different address.
    v_cta := v_app || '/' || coalesce('?ref=' || r.ref, '');
    v_unsub := v_app || '/unsubscribe?t=' || r.unsub_token::text;

    perform net.http_post(
      url     := 'https://api.resend.com/emails',
      headers := jsonb_build_object('Content-Type', 'application/json',
                                    'Authorization', 'Bearer ' || v_key),
      body    := jsonb_build_object(
        'from', p_from, 'to', r.email, 'subject', v_subj,
        'html', replace(replace(v_html, '@@CTA@@', v_cta), '@@UNSUB@@', v_unsub),
        'text', replace(replace(v_text, '@@CTA@@', v_cta), '@@UNSUB@@', v_unsub),
        -- Gmail and Yahoo require one-click unsubscribe on bulk mail. Without
        -- it this send damages deliverability for password resets too.
        'headers', jsonb_build_object(
          'List-Unsubscribe', '<' || v_unsub || '>',
          'List-Unsubscribe-Post', 'List-Unsubscribe=One-Click'))
    );

    -- pg_net is FIRE AND FORGET: http_post queues the request and returns
    -- immediately, so there is no delivery to confirm inside this loop. Stamped
    -- optimistically, which is the right trade — a duplicate is worse than a
    -- miss here, and the reconcile query below finds anything Resend refused.
    update public.waitlist set launch_emailed_at = now() where id = r.id;
    v_sent := v_sent + 1;
  end loop;

  select count(*) into v_left from public.waitlist
   where unsubscribed_at is null and launch_emailed_at is null;

  return query select v_sent, v_left,
    case when v_left > 0
      then 'Queued ' || v_sent || '. ' || v_left || ' still to go — run it again.'
      else 'Queued ' || v_sent || '. Nobody left to email.' end;
end;
$fn$;

revoke execute on function public.announce_launch(int, text, text) from public, anon;
grant  execute on function public.announce_launch(int, text, text) to authenticated;

-- =============================================================================
-- HOW TO USE IT
--
--   1. Test it on yourself. Sends one email, changes nothing:
--        select * from public.announce_launch(p_test_to => 'you@example.com');
--
--   2. See who is queued up, without sending:
--        select count(*) from public.waitlist
--         where unsubscribed_at is null and launch_emailed_at is null;
--
--   3. Send. Start small — 5 proves the whole path before it costs anything:
--        select * from public.announce_launch(5);
--        select * from public.announce_launch(50);   -- repeat until 0 remain
--
--   4. Did they actually go? pg_net records every response:
--        select r.status_code, count(*)
--          from net._http_response r
--         where r.created > now() - interval '1 hour'
--         group by 1;
--
--   5. Anything Resend refused was still marked as sent, because pg_net cannot
--      report failure synchronously. This puts those back in the queue — but
--      only run it if step 4 shows non-2xx responses, or you will re-send to
--      people who received it:
--        -- update public.waitlist set launch_emailed_at = null
--        --  where launch_emailed_at > now() - interval '1 hour';
-- =============================================================================
