-- =============================================================================
-- Refresh the launch email copy. NOTHING IS SENT BY RUNNING THIS.
--
-- GENERATED by scripts/gen-announce-sql.mjs --email-only. The email HTML lives
-- inside the function body, so new wording only reaches the database when the
-- function is replaced — regenerating the repo file does not touch Postgres,
-- and the button will keep sending the previous copy until this is run.
--
-- Safe to run repeatedly: create or replace, no drop, no data touched. It does
-- not clear launch_emailed_at, so anyone already emailed stays emailed.
--
-- The last statement checks itself and prints the verdict, so there is nothing
-- to remember to run afterwards and nothing to eyeball in an inbox.
-- =============================================================================

-- --- The sender ---------------------------------------------------------------

create or replace function public.announce_launch(
  p_limit    int  default 50,
  p_test_to  text default null,
  -- MATCHES cloudflare/wrangler.toml's REMINDER_FROM, which is the address the
  -- Worker's reminder emails already go out from — so it is a mailbox on a
  -- domain Resend has already verified. The default used to be hello@, which
  -- nothing sends from: a launch blast is the worst possible moment to find out
  -- an address is unconfigured, and the failure would be one opaque 4xx per
  -- recipient.
  p_from     text default 'PocketAthlete <info@pocketathlete.com>'
)
returns table (emailed int, remaining int, note text)
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  -- copy-id: 39248fb9de92
  -- Fingerprint of the email copy below, kept where Postgres stores it verbatim.
  -- The self-check at the bottom of announce-launch-update.sql looks for exactly
  -- this string, which is how you tell a paste that took from one that did not.
  v_key   text;
  v_html  text := $mail$<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Pocket Athlete is live 🔥 you're in</title></head>
<body style="margin:0;padding:0;background:#0b0f0d;">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;">It's open. 33 positions, 6 sports, and your first plan is two minutes away.</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#0b0f0d;padding:20px 12px;">
<tr><td align="center">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#121714;border-radius:20px;padding:30px 26px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">

  <tr><td style="padding-bottom:20px;">
    <span style="font-size:18px;font-weight:800;letter-spacing:-0.01em;color:#f1f5f3;">
      <span style="color:#e3b53f;">&#9670;</span> PocketAthlete
    </span>
  </td></tr>

  <tr><td style="font-size:12px;font-weight:800;letter-spacing:0.16em;text-transform:uppercase;color:#e3b53f;padding-bottom:8px;">
    Now live
  </td></tr>

  <tr><td style="font-size:34px;line-height:1.1;font-weight:800;letter-spacing:-0.02em;color:#f1f5f3;padding-bottom:12px;">
    Pocket Athlete<br><span style="color:#e3b53f;">is live.</span>
  </td></tr>

  <tr><td style="font-size:16px;line-height:1.55;color:#9fb0a8;padding-bottom:20px;">
    You put your name down before there was anything to see. It's open now — and you're
    getting this before anyone else.
  </td></tr>

  <tr><td style="padding-bottom:12px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
      <tr><td align="center" bgcolor="#e3b53f" style="background:#e3b53f;border-radius:999px;">
        <a href="@@CTA@@" style="display:block;padding:17px 20px;font-size:18px;font-weight:800;color:#0b0f0d;text-decoration:none;letter-spacing:-0.01em;">Open Pocket Athlete →</a>
      </td></tr>
    </table>
  </td></tr>

  <tr><td align="center" style="font-size:13px;line-height:1.5;color:#9fb0a8;padding-bottom:26px;">
    Free to start. No card. About two minutes to your first four-week block.
  </td></tr>

  <tr><td style="border-top:1px solid rgba(255,255,255,0.07);padding-top:26px;font-size:23px;line-height:1.22;font-weight:800;letter-spacing:-0.01em;color:#f1f5f3;padding-bottom:10px;">
    Most plans know your sport.<br><span style="color:#e3b53f;">This one knows your position.</span>
  </td></tr>

  <tr><td style="font-size:15px;line-height:1.6;color:#9fb0a8;padding-bottom:18px;">
    A prop and a winger need different bodies, so they get different sessions.
  </td></tr>

  <tr><td style="padding-bottom:20px;"><span style="display:inline-block;background:rgba(227,181,63,0.10);border:1px solid rgba(227,181,63,0.22);color:#e3b53f;font-size:12px;font-weight:700;padding:6px 11px;border-radius:999px;margin:0 5px 7px 0;white-space:nowrap;">Prop</span><span style="display:inline-block;background:rgba(227,181,63,0.10);border:1px solid rgba(227,181,63,0.22);color:#e3b53f;font-size:12px;font-weight:700;padding:6px 11px;border-radius:999px;margin:0 5px 7px 0;white-space:nowrap;">Winger</span><span style="display:inline-block;background:rgba(227,181,63,0.10);border:1px solid rgba(227,181,63,0.22);color:#e3b53f;font-size:12px;font-weight:700;padding:6px 11px;border-radius:999px;margin:0 5px 7px 0;white-space:nowrap;">Goalkeeper</span><span style="display:inline-block;background:rgba(227,181,63,0.10);border:1px solid rgba(227,181,63,0.22);color:#e3b53f;font-size:12px;font-weight:700;padding:6px 11px;border-radius:999px;margin:0 5px 7px 0;white-space:nowrap;">Point guard</span><span style="display:inline-block;background:rgba(227,181,63,0.10);border:1px solid rgba(227,181,63,0.22);color:#e3b53f;font-size:12px;font-weight:700;padding:6px 11px;border-radius:999px;margin:0 5px 7px 0;white-space:nowrap;">Scrum-half</span><span style="display:inline-block;background:rgba(227,181,63,0.10);border:1px solid rgba(227,181,63,0.22);color:#e3b53f;font-size:12px;font-weight:700;padding:6px 11px;border-radius:999px;margin:0 5px 7px 0;white-space:nowrap;">Marathon</span><span style="display:inline-block;background:rgba(227,181,63,0.10);border:1px solid rgba(227,181,63,0.22);color:#e3b53f;font-size:12px;font-weight:700;padding:6px 11px;border-radius:999px;margin:0 5px 7px 0;white-space:nowrap;">+27 more</span></td></tr>

  <tr><td style="padding-bottom:26px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0"
      style="background:rgba(255,255,255,0.03);border-radius:14px;padding:14px 6px;">
      <tr><td align="center" style="padding:0 4px;">
        <div style="font-size:22px;font-weight:800;color:#f1f5f3;">33</div>
        <div style="font-size:10px;letter-spacing:0.08em;text-transform:uppercase;color:#6b7a73;">positions</div>
      </td><td align="center" style="padding:0 4px;">
        <div style="font-size:22px;font-weight:800;color:#f1f5f3;">6</div>
        <div style="font-size:10px;letter-spacing:0.08em;text-transform:uppercase;color:#6b7a73;">sports</div>
      </td><td align="center" style="padding:0 4px;">
        <div style="font-size:22px;font-weight:800;color:#f1f5f3;">136</div>
        <div style="font-size:10px;letter-spacing:0.08em;text-transform:uppercase;color:#6b7a73;">challenges</div>
      </td><td align="center" style="padding:0 4px;">
        <div style="font-size:22px;font-weight:800;color:#f1f5f3;">62</div>
        <div style="font-size:10px;letter-spacing:0.08em;text-transform:uppercase;color:#6b7a73;">badges</div>
      </td></tr>
    </table>
  </td></tr>

  <tr><td style="font-size:12px;font-weight:800;letter-spacing:0.14em;text-transform:uppercase;color:#6b7a73;padding-bottom:16px;">
    What's waiting for you
  </td></tr>

  <tr><td style="padding-bottom:18px;">
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr>
      <td width="34" valign="top" style="font-size:20px;line-height:1.3;">🎥</td>
      <td valign="top">
        <div style="font-size:15px;font-weight:700;color:#f1f5f3;padding-bottom:3px;">Film a rep, watch it get read</div>
        <div style="font-size:14px;line-height:1.55;color:#9fb0a8;">Depth, tempo, bar path, the knee caving in on rep 8 — with the drills to fix what it finds. The analysis runs on your own phone.</div>
      </td>
    </tr></table>
  </td></tr>
  <tr><td style="padding-bottom:18px;">
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr>
      <td width="34" valign="top" style="font-size:20px;line-height:1.3;">🩺</td>
      <td valign="top">
        <div style="font-size:15px;font-weight:700;color:#f1f5f3;padding-bottom:3px;">A plan that reacts</div>
        <div style="font-size:14px;line-height:1.55;color:#9fb0a8;">Slept badly? Three taps and today eases off by itself. It watches your training load and tells you to back off before the niggle, not after.</div>
      </td>
    </tr></table>
  </td></tr>
  <tr><td style="padding-bottom:18px;">
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr>
      <td width="34" valign="top" style="font-size:20px;line-height:1.3;">🍽️</td>
      <td valign="top">
        <div style="font-size:15px;font-weight:700;color:#f1f5f3;padding-bottom:3px;">Food that adds up</div>
        <div style="font-size:14px;line-height:1.55;color:#9fb0a8;">Calorie and macro targets, meal plans built round your training, and a shopping list with prices on it.</div>
      </td>
    </tr></table>
  </td></tr>
  <tr><td style="padding-bottom:18px;">
    <table role="presentation" cellpadding="0" cellspacing="0" width="100%"><tr>
      <td width="34" valign="top" style="font-size:20px;line-height:1.3;">🏆</td>
      <td valign="top">
        <div style="font-size:15px;font-weight:700;color:#f1f5f3;padding-bottom:3px;">Something to chase</div>
        <div style="font-size:14px;line-height:1.55;color:#9fb0a8;">136 challenges, 62 badges and a rank ladder from Iron to Legend. It pays you for rest days too, not just for grinding.</div>
      </td>
    </tr></table>
  </td></tr>

  <tr><td style="padding-top:8px;"></td></tr>
  <tr><td style="padding-bottom:12px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
      <tr><td align="center" bgcolor="#e3b53f" style="background:#e3b53f;border-radius:999px;">
        <a href="@@CTA@@" style="display:block;padding:17px 20px;font-size:18px;font-weight:800;color:#0b0f0d;text-decoration:none;letter-spacing:-0.01em;">Build my first plan →</a>
      </td></tr>
    </table>
  </td></tr>

  <tr><td style="border-top:1px solid rgba(255,255,255,0.08);padding-top:22px;font-size:12px;line-height:1.6;color:#6b7a73;">
    You're getting this because you joined the Pocket Athlete waitlist.<br>
    <a href="@@UNSUB@@" style="color:#9fb0a8;text-decoration:underline;">Unsubscribe</a> — one click, no questions.
  </td></tr>

</table>
</td></tr></table>
</body></html>$mail$;
  v_text  text := $mail$POCKET ATHLETE IS LIVE.

You put your name down before there was anything to see. It's open now, and
you're getting this before anyone else.

Open it: @@CTA@@

Free to start. No card. About two minutes to your first four-week block.

---

MOST PLANS KNOW YOUR SPORT. THIS ONE KNOWS YOUR POSITION.

A prop and a winger need different bodies, so they get different sessions.
33 positions across 6 sports, each with their own movements, drills and
challenges. Not one generic plan with your sport's name on the front.

WHAT'S WAITING FOR YOU

- Film a rep, watch it get read. Depth, tempo, bar path, the knee caving in
  on rep 8 - with the drills to fix what it finds. The analysis runs on your
  own phone.
- A plan that reacts. Slept badly? Three taps and today eases off by itself.
  It watches your training load and tells you to back off BEFORE the niggle.
- Food that adds up. Calorie and macro targets, meal plans built round your
  training, a shopping list with prices on it.
- Something to chase. 136 challenges, 62 badges, and a rank ladder from Iron
  to Legend. It pays you for rest days too, not just for grinding.

Start here: @@CTA@@

See you in there.

-
You're getting this because you joined the Pocket Athlete waitlist.
Unsubscribe: @@UNSUB@@$mail$;
  v_subj  text := $mail$Pocket Athlete is live 🔥 you're in$mail$;
  v_app   text := $mail$https://pocketathlete.com$mail$;
  r       record;
  v_cta   text;
  v_unsub text;
  v_sent  int := 0;
  v_left  int;
begin
  if not public.is_admin() then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  -- SEVERAL NAMES, because the key may already be here under one of them.
  -- Vault is not where the Edge Functions keep theirs — those read
  -- Deno.env.get('RESEND_API_KEY'), which is a function-runtime secret that
  -- Postgres cannot see. Same key, different cupboard. Checking the obvious
  -- spellings costs nothing and saves a confusing "it is already set" round.
  select decrypted_secret into v_key
    from vault.decrypted_secrets
   where name in ('resend_api_key', 'RESEND_API_KEY', 'resend', 'RESEND')
   order by case name when 'resend_api_key' then 0 else 1 end
   limit 1;

  if v_key is null then
    raise exception
      'No Resend key in Vault. See what is there:  select name from vault.secrets;  '
      'Then add it:  select vault.create_secret(''re_xxx'', ''resend_api_key'');  '
      'Note this is separate from the Edge Function secret of the same name - Postgres cannot read those.';
  end if;

  -- ONE ADDRESS, TOUCHING NOTHING. Returns before the real query so a test can
  -- be fired as often as you like while tweaking the copy — if it consumed a
  -- place in the batch, checking the email would remove people from the send it
  -- was checking.
  if p_test_to is not null then
    v_cta   := v_app || '/';
    v_unsub := v_app || '/unsubscribe?t=' || gen_random_uuid()::text;
    perform net.http_post(
      url     := 'https://api.resend.com/emails',
      headers := jsonb_build_object('Content-Type', 'application/json',
                                    'Authorization', 'Bearer ' || v_key),
      body    := jsonb_build_object(
        'from', p_from, 'to', p_test_to,
        'subject', '[TEST] ' || v_subj,
        'html', replace(replace(v_html, '@@CTA@@', v_cta), '@@UNSUB@@', v_unsub),
        'text', replace(replace(v_text, '@@CTA@@', v_cta), '@@UNSUB@@', v_unsub))
    );
    return query select 0, 0,
      'Test queued to ' || p_test_to || '. Nobody on the waitlist was emailed, marked or skipped.';
    return;
  end if;

  -- Never anyone who left, never anyone already told. The stamp is what makes
  -- pressing this twice safe, and it is why it can be run in batches.
  for r in
    select w.id, w.email, w.unsub_token,
           coalesce(nullif(trim(w.referral_code), ''), nullif(trim(w.source), '')) as ref
      from public.waitlist w
     where w.unsubscribed_at is null
       and w.launch_emailed_at is null
     order by w.created_at
     limit greatest(1, p_limit)
  loop
    -- The affiliate code that brought them in. Attribution does not depend on
    -- it — 0057 binds the email to its referrer permanently and signup reads
    -- that ledger — but it covers someone signing up with a different address.
    v_cta := v_app || '/' || coalesce('?ref=' || r.ref, '');
    v_unsub := v_app || '/unsubscribe?t=' || r.unsub_token::text;

    perform net.http_post(
      url     := 'https://api.resend.com/emails',
      headers := jsonb_build_object('Content-Type', 'application/json',
                                    'Authorization', 'Bearer ' || v_key),
      body    := jsonb_build_object(
        'from', p_from, 'to', r.email, 'subject', v_subj,
        'html', replace(replace(v_html, '@@CTA@@', v_cta), '@@UNSUB@@', v_unsub),
        'text', replace(replace(v_text, '@@CTA@@', v_cta), '@@UNSUB@@', v_unsub),
        -- Gmail and Yahoo require one-click unsubscribe on bulk mail. Without
        -- it this send damages deliverability for password resets too.
        'headers', jsonb_build_object(
          'List-Unsubscribe', '<' || v_unsub || '>',
          'List-Unsubscribe-Post', 'List-Unsubscribe=One-Click'))
    );

    -- pg_net is FIRE AND FORGET: http_post queues the request and returns
    -- immediately, so there is no delivery to confirm inside this loop. Stamped
    -- optimistically, which is the right trade — a duplicate is worse than a
    -- miss here, and the reconcile query below finds anything Resend refused.
    update public.waitlist set launch_emailed_at = now() where id = r.id;
    v_sent := v_sent + 1;
  end loop;

  select count(*) into v_left from public.waitlist
   where unsubscribed_at is null and launch_emailed_at is null;

  return query select v_sent, v_left,
    case when v_left > 0
      then 'Queued ' || v_sent || '. ' || v_left || ' still to go — run it again.'
      else 'Queued ' || v_sent || '. Nobody left to email.' end;
end;
$fn$;

revoke execute on function public.announce_launch(int, text, text) from public, anon;
grant  execute on function public.announce_launch(int, text, text) to authenticated;

-- --- Did it take? -------------------------------------------------------------
-- Reads one row from the catalogue. Sends nothing, changes nothing.
--
-- If this says INSTALLED, the new copy is live and the admin test button will
-- send it. If it says anything else, the statements above did not run — the
-- usual cause is a partial paste, because the email HTML is one long string and
-- it has to go in whole.

select case
         when p.prosrc like '%copy-id: 39248fb9de92%'
           then 'INSTALLED - new copy is live (copy-id 39248fb9de92). Send yourself a test.'
         when p.prosrc is not null
           then 'NOT INSTALLED - announce_launch still holds different copy. Re-paste this whole file.'
       end as result
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
 where p.proname = 'announce_launch' and n.nspname = 'public';
