// GENERATED by scripts/build-exercise-art.mjs — do not edit by hand.
//
// Exercises we have real anatomical artwork for, mapped to the file stem under
// public/exercise-art. Two frames each: `-start.svg` and `-end.svg`.
//
// Everything NOT in here falls back to the drawn figure in
// components/ExerciseDemo.tsx, which is most of the sport-specific work — no
// anatomy library has a cone weave or a Copenhagen plank. See the script for
// why the pairing refuses more than it accepts.

/**
 * Required by the licence, and shown in the app — see components/ArtCredit.tsx.
 *
 * CC BY-SA 4.0 binds ADAPTATIONS, so these files are copied and never edited:
 * recolouring one would put that version under the same licence. If you ever
 * do need to modify one, that modified file has to ship under CC BY-SA 4.0 too.
 */
export const ART_CREDIT = {
  work: "Everkinetic",
  author: "Greg Priday",
  source: "https://github.com/everkinetic/data",
  licence: "CC BY-SA 4.0",
  licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
} as const;

export const EXERCISE_ART: Record<string, string> = {
  "Barbell Curl": "barbell-curl",
  "Barbell Front Squat": "barbell-front-squat",
  "Barbell Hack Squat": "barbell-hack-squat",
  "Barbell Lunge": "barbell-lunge",
  "Barbell Shrug": "barbell-shrug",
  "Bench Dips": "bench-dips",
  "Bench Press": "bench-press",
  "Cable Hammer Curl": "cable-hammer-curl",
  "Cable Shrug": "cable-shrug",
  "Cable Tricep Pushdown": "cable-tricep-pushdown",
  "Cable Upright Row": "cable-upright-row",
  "Close Grip Bench Press": "close-grip-bench-press",
  "Crunches": "crunches",
  "Decline Bench Press": "decline-bench-press",
  "Decline Crunch": "decline-crunch",
  "Decline Dumbbell Bench Press": "decline-dumbbell-bench-press",
  "Decline Dumbbell Fly": "decline-dumbbell-fly",
  "Dips": "dips",
  "Donkey Calf Raise": "donkey-calf-raise",
  "Dumbbell Bench Press": "dumbbell-bench-press",
  "Dumbbell Concentration Curl": "dumbbell-concentration-curl",
  "Dumbbell Curl": "dumbbell-curl",
  "Dumbbell Fly": "dumbbell-fly",
  "Dumbbell Front Raise": "dumbbell-front-raise",
  "Dumbbell Lateral Raise": "dumbbell-lateral-raise",
  "Dumbbell Lunge": "dumbbell-lunge",
  "Dumbbell Reverse Curl": "dumbbell-reverse-curl",
  "Dumbbell Side Bend": "dumbbell-side-bend",
  "Dumbbell Squat": "dumbbell-squat",
  "Dumbbell Tricep Kickback": "dumbbell-tricep-kickback",
  "Dumbbell Upright Row": "dumbbell-upright-row",
  "EZ Bar Curl": "ez-bar-curl",
  "Flutter Kicks": "flutter-kicks",
  "Good Morning": "good-morning",
  "Hack Squat": "hack-squat",
  "Hip Adduction": "hip-adduction",
  "Incline Bench Press": "incline-bench-press",
  "Incline Dumbbell Bench Press": "incline-dumbbell-bench-press",
  "Incline Dumbbell Fly": "incline-dumbbell-fly",
  "JM Press": "jm-press",
  "Leg Extension": "leg-extension",
  "Leg Press": "leg-press",
  "Lunge": "lunge",
  "Lying Cable Curl": "lying-cable-curl",
  "Lying Dumbbell Tricep Extension": "lying-dumbbell-tricep-extension",
  "Lying Leg Curl": "lying-leg-curl",
  "Lying Tricep Extension": "lying-tricep-extension",
  "Machine Bicep Curl": "machine-bicep-curl",
  "Machine Tricep Extension": "machine-tricep-extension",
  "Overhead Cable Curl": "overhead-cable-curl",
  "Overhead Squat": "overhead-squat",
  "Preacher Curl": "preacher-curl",
  "Pull Ups": "pull-ups",
  "Push Ups": "push-ups",
  "Reverse Grip Tricep Pushdown": "reverse-grip-tricep-pushdown",
  "Seated Cable Row": "seated-cable-row",
  "Seated Calf Raise": "seated-calf-raise",
  "Seated Dumbbell Curl": "seated-dumbbell-curl",
  "Seated Leg Curl": "seated-leg-curl",
  "Single Leg Squat": "single-leg-squat",
  "Smith Machine Bench Press": "smith-machine-bench-press",
  "Smith Machine Shrug": "smith-machine-shrug",
  "Smith Machine Squat": "smith-machine-squat",
  "Spider Curl": "spider-curl",
  "Standing Calf Raise": "standing-calf-raise",
  "Standing Leg Curl": "standing-leg-curl",
  "Superman": "superman",
  "T Bar Row": "t-bar-row",
  "Tate Press": "tate-press",
  "Tricep Extension": "tricep-extension",
  "Tricep Pushdown": "tricep-pushdown",
  "Tricep Rope Pushdown": "tricep-rope-pushdown",
  "Upright Row": "upright-row",
  "Walking Lunge": "walking-lunge",
  "Wide Grip Bench Press": "wide-grip-bench-press",
  "Zottman Curl": "zottman-curl",
};

/** The two frames for an exercise, or null when we only have the drawn figure. */
export function artFor(name: string): { start: string; end: string } | null {
  const key = EXERCISE_ART[name.trim()];
  return key ? { start: `/exercise-art/${key}-start.svg`, end: `/exercise-art/${key}-end.svg` } : null;
}
