// GENERATED by scripts/build-exercise-art.mjs — do not edit by hand.
//
// Every exercise we have a real picture for, and which library it came from.
// Two frames each, `-start` and `-end`, under public/exercise-art.
//
// Anything NOT here falls back to the drawn figure in
// components/ExerciseDemo.tsx — most of the sport-specific work, because no
// exercise library has a cone weave or a Copenhagen plank. See the script for
// why the pairing refuses more than it accepts.

export type ArtSource = "everkinetic" | "free-exercise-db";

/**
 * Where each library came from and what it asks for in return.
 *
 * Everkinetic is CC BY-SA 4.0, so it must be credited — and share-alike binds
 * ADAPTATIONS, which is why the pipeline copies files and never edits them.
 * free-exercise-db is public domain and asks for nothing; it is credited anyway,
 * because taking someone's work silently because you legally may is a poor way
 * to treat the people who make the free things.
 */
export const ART_SOURCES: Record<ArtSource, {
  work: string; author: string; source: string; licence: string; licenceUrl: string;
}> = {
  everkinetic: {
    work: "Everkinetic",
    author: "Greg Priday",
    source: "https://github.com/everkinetic/data",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
  },
  "free-exercise-db": {
    work: "Free Exercise DB",
    author: "yuhonas",
    source: "https://github.com/yuhonas/free-exercise-db",
    licence: "Public domain",
    licenceUrl: "https://unlicense.org/",
  },
};

/** The credit for the illustrated set, kept for callers that predate the photos. */
export const ART_CREDIT = ART_SOURCES.everkinetic;

interface ArtEntry { key: string; ext: "svg" | "jpg"; from: ArtSource }

export const EXERCISE_ART: Record<string, ArtEntry> = {
  "Arnold Press": { key: "arnold-press", ext: "jpg", from: "free-exercise-db" },
  "Back Extension": { key: "back-extension", ext: "jpg", from: "free-exercise-db" },
  "Barbell Curl": { key: "barbell-curl", ext: "svg", from: "everkinetic" },
  "Barbell Deadlift": { key: "barbell-deadlift", ext: "jpg", from: "free-exercise-db" },
  "Barbell Front Squat": { key: "barbell-front-squat", ext: "svg", from: "everkinetic" },
  "Barbell Glute Bridge": { key: "barbell-glute-bridge", ext: "jpg", from: "free-exercise-db" },
  "Barbell Hack Squat": { key: "barbell-hack-squat", ext: "svg", from: "everkinetic" },
  "Barbell Hip Thrust": { key: "barbell-hip-thrust", ext: "jpg", from: "free-exercise-db" },
  "Barbell Lunge": { key: "barbell-lunge", ext: "svg", from: "everkinetic" },
  "Barbell Shrug": { key: "barbell-shrug", ext: "svg", from: "everkinetic" },
  "Bench Dips": { key: "bench-dips", ext: "svg", from: "everkinetic" },
  "Bench Press": { key: "bench-press", ext: "svg", from: "everkinetic" },
  "Bent Over Row": { key: "bent-over-row", ext: "jpg", from: "free-exercise-db" },
  "Bodyweight Squat": { key: "bodyweight-squat", ext: "jpg", from: "free-exercise-db" },
  "Box Squat": { key: "box-squat", ext: "jpg", from: "free-exercise-db" },
  "Cable Crunch": { key: "cable-crunch", ext: "jpg", from: "free-exercise-db" },
  "Cable Hammer Curl": { key: "cable-hammer-curl", ext: "svg", from: "everkinetic" },
  "Cable Overhead Tricep Extension": { key: "cable-overhead-tricep-extension", ext: "jpg", from: "free-exercise-db" },
  "Cable Shrug": { key: "cable-shrug", ext: "svg", from: "everkinetic" },
  "Cable Tricep Pushdown": { key: "cable-tricep-pushdown", ext: "svg", from: "everkinetic" },
  "Cable Upright Row": { key: "cable-upright-row", ext: "svg", from: "everkinetic" },
  "Chest Press": { key: "chest-press", ext: "jpg", from: "free-exercise-db" },
  "Clean": { key: "clean", ext: "jpg", from: "free-exercise-db" },
  "Clean and Jerk": { key: "clean-and-jerk", ext: "jpg", from: "free-exercise-db" },
  "Clean and Press": { key: "clean-and-press", ext: "jpg", from: "free-exercise-db" },
  "Clean Pull": { key: "clean-pull", ext: "jpg", from: "free-exercise-db" },
  "Close Grip Bench Press": { key: "close-grip-bench-press", ext: "svg", from: "everkinetic" },
  "Crunches": { key: "crunches", ext: "svg", from: "everkinetic" },
  "Decline Bench Press": { key: "decline-bench-press", ext: "svg", from: "everkinetic" },
  "Decline Crunch": { key: "decline-crunch", ext: "svg", from: "everkinetic" },
  "Decline Dumbbell Bench Press": { key: "decline-dumbbell-bench-press", ext: "svg", from: "everkinetic" },
  "Decline Dumbbell Fly": { key: "decline-dumbbell-fly", ext: "svg", from: "everkinetic" },
  "Decline Push Up": { key: "decline-push-up", ext: "jpg", from: "free-exercise-db" },
  "Deficit Deadlift": { key: "deficit-deadlift", ext: "jpg", from: "free-exercise-db" },
  "Dips": { key: "dips", ext: "svg", from: "everkinetic" },
  "Donkey Calf Raise": { key: "donkey-calf-raise", ext: "svg", from: "everkinetic" },
  "Dumbbell Bench Press": { key: "dumbbell-bench-press", ext: "svg", from: "everkinetic" },
  "Dumbbell Calf Raise": { key: "dumbbell-calf-raise", ext: "jpg", from: "free-exercise-db" },
  "Dumbbell Concentration Curl": { key: "dumbbell-concentration-curl", ext: "svg", from: "everkinetic" },
  "Dumbbell Curl": { key: "dumbbell-curl", ext: "svg", from: "everkinetic" },
  "Dumbbell Floor Press": { key: "dumbbell-floor-press", ext: "jpg", from: "free-exercise-db" },
  "Dumbbell Fly": { key: "dumbbell-fly", ext: "svg", from: "everkinetic" },
  "Dumbbell Front Raise": { key: "dumbbell-front-raise", ext: "svg", from: "everkinetic" },
  "Dumbbell Lateral Raise": { key: "dumbbell-lateral-raise", ext: "svg", from: "everkinetic" },
  "Dumbbell Lunge": { key: "dumbbell-lunge", ext: "svg", from: "everkinetic" },
  "Dumbbell Reverse Curl": { key: "dumbbell-reverse-curl", ext: "svg", from: "everkinetic" },
  "Dumbbell Shoulder Press": { key: "dumbbell-shoulder-press", ext: "jpg", from: "free-exercise-db" },
  "Dumbbell Shrug": { key: "dumbbell-shrug", ext: "jpg", from: "free-exercise-db" },
  "Dumbbell Side Bend": { key: "dumbbell-side-bend", ext: "svg", from: "everkinetic" },
  "Dumbbell Split Squat": { key: "dumbbell-split-squat", ext: "jpg", from: "free-exercise-db" },
  "Dumbbell Squat": { key: "dumbbell-squat", ext: "svg", from: "everkinetic" },
  "Dumbbell Tricep Kickback": { key: "dumbbell-tricep-kickback", ext: "svg", from: "everkinetic" },
  "Dumbbell Upright Row": { key: "dumbbell-upright-row", ext: "svg", from: "everkinetic" },
  "EZ Bar Curl": { key: "ez-bar-curl", ext: "svg", from: "everkinetic" },
  "Face Pull": { key: "face-pull", ext: "jpg", from: "free-exercise-db" },
  "Floor Press": { key: "floor-press", ext: "jpg", from: "free-exercise-db" },
  "Flutter Kicks": { key: "flutter-kicks", ext: "svg", from: "everkinetic" },
  "Glute Bridge": { key: "glute-bridge", ext: "jpg", from: "free-exercise-db" },
  "Glute Ham Raise": { key: "glute-ham-raise", ext: "jpg", from: "free-exercise-db" },
  "Glute Kickback": { key: "glute-kickback", ext: "jpg", from: "free-exercise-db" },
  "Good Morning": { key: "good-morning", ext: "svg", from: "everkinetic" },
  "Hack Squat": { key: "hack-squat", ext: "svg", from: "everkinetic" },
  "Hammer Curl": { key: "hammer-curl", ext: "jpg", from: "free-exercise-db" },
  "Handstand Push Ups": { key: "handstand-push-ups", ext: "jpg", from: "free-exercise-db" },
  "Hang Clean": { key: "hang-clean", ext: "jpg", from: "free-exercise-db" },
  "Hanging Leg Raise": { key: "hanging-leg-raise", ext: "jpg", from: "free-exercise-db" },
  "Hip Adduction": { key: "hip-adduction", ext: "svg", from: "everkinetic" },
  "Hip Extension": { key: "hip-extension", ext: "jpg", from: "free-exercise-db" },
  "Incline Bench Press": { key: "incline-bench-press", ext: "svg", from: "everkinetic" },
  "Incline Bicep Curl": { key: "incline-bicep-curl", ext: "jpg", from: "free-exercise-db" },
  "Incline Dumbbell Bench Press": { key: "incline-dumbbell-bench-press", ext: "svg", from: "everkinetic" },
  "Incline Dumbbell Curl": { key: "incline-dumbbell-curl", ext: "jpg", from: "free-exercise-db" },
  "Incline Dumbbell Fly": { key: "incline-dumbbell-fly", ext: "svg", from: "everkinetic" },
  "Incline Hammer Curl": { key: "incline-hammer-curl", ext: "jpg", from: "free-exercise-db" },
  "Incline Push Up": { key: "incline-push-up", ext: "jpg", from: "free-exercise-db" },
  "Inverted Row": { key: "inverted-row", ext: "jpg", from: "free-exercise-db" },
  "JM Press": { key: "jm-press", ext: "svg", from: "everkinetic" },
  "Leg Curl": { key: "leg-curl", ext: "jpg", from: "free-exercise-db" },
  "Leg Extension": { key: "leg-extension", ext: "svg", from: "everkinetic" },
  "Leg Press": { key: "leg-press", ext: "svg", from: "everkinetic" },
  "Lunge": { key: "lunge", ext: "svg", from: "everkinetic" },
  "Lying Cable Curl": { key: "lying-cable-curl", ext: "svg", from: "everkinetic" },
  "Lying Dumbbell Tricep Extension": { key: "lying-dumbbell-tricep-extension", ext: "svg", from: "everkinetic" },
  "Lying Leg Curl": { key: "lying-leg-curl", ext: "svg", from: "everkinetic" },
  "Lying Tricep Extension": { key: "lying-tricep-extension", ext: "svg", from: "everkinetic" },
  "Machine Bicep Curl": { key: "machine-bicep-curl", ext: "svg", from: "everkinetic" },
  "Machine Calf Raise": { key: "machine-calf-raise", ext: "jpg", from: "free-exercise-db" },
  "Machine Shoulder Press": { key: "machine-shoulder-press", ext: "jpg", from: "free-exercise-db" },
  "Machine Tricep Extension": { key: "machine-tricep-extension", ext: "svg", from: "everkinetic" },
  "Mountain Climbers": { key: "mountain-climbers", ext: "jpg", from: "free-exercise-db" },
  "One Arm Lat Pulldown": { key: "one-arm-lat-pulldown", ext: "jpg", from: "free-exercise-db" },
  "One Arm Seated Cable Row": { key: "one-arm-seated-cable-row", ext: "jpg", from: "free-exercise-db" },
  "Overhead Cable Curl": { key: "overhead-cable-curl", ext: "svg", from: "everkinetic" },
  "Overhead Squat": { key: "overhead-squat", ext: "svg", from: "everkinetic" },
  "Pistol Squat": { key: "pistol-squat", ext: "jpg", from: "free-exercise-db" },
  "Plank": { key: "plank", ext: "jpg", from: "free-exercise-db" },
  "Power Snatch": { key: "power-snatch", ext: "jpg", from: "free-exercise-db" },
  "Preacher Curl": { key: "preacher-curl", ext: "svg", from: "everkinetic" },
  "Pull Ups": { key: "pull-ups", ext: "svg", from: "everkinetic" },
  "Push Press": { key: "push-press", ext: "jpg", from: "free-exercise-db" },
  "Push Ups": { key: "push-ups", ext: "svg", from: "everkinetic" },
  "Rack Pull": { key: "rack-pull", ext: "jpg", from: "free-exercise-db" },
  "Rear Delt Fly": { key: "rear-delt-fly", ext: "jpg", from: "free-exercise-db" },
  "Reverse Barbell Curl": { key: "reverse-barbell-curl", ext: "jpg", from: "free-exercise-db" },
  "Reverse Grip Tricep Pushdown": { key: "reverse-grip-tricep-pushdown", ext: "svg", from: "everkinetic" },
  "Reverse Hyperextension": { key: "reverse-hyperextension", ext: "jpg", from: "free-exercise-db" },
  "Reverse Lunge": { key: "reverse-lunge", ext: "jpg", from: "free-exercise-db" },
  "Ring Dips": { key: "ring-dips", ext: "jpg", from: "free-exercise-db" },
  "Romanian Deadlift": { key: "romanian-deadlift", ext: "jpg", from: "free-exercise-db" },
  "Russian Twist": { key: "russian-twist", ext: "jpg", from: "free-exercise-db" },
  "Scissor Kicks": { key: "scissor-kicks", ext: "jpg", from: "free-exercise-db" },
  "Seated Cable Row": { key: "seated-cable-row", ext: "svg", from: "everkinetic" },
  "Seated Calf Raise": { key: "seated-calf-raise", ext: "svg", from: "everkinetic" },
  "Seated Dumbbell Curl": { key: "seated-dumbbell-curl", ext: "svg", from: "everkinetic" },
  "Seated Leg Curl": { key: "seated-leg-curl", ext: "svg", from: "everkinetic" },
  "Seated Shoulder Press": { key: "seated-shoulder-press", ext: "jpg", from: "free-exercise-db" },
  "Shoulder Press": { key: "shoulder-press", ext: "jpg", from: "free-exercise-db" },
  "Side Leg Raise": { key: "side-leg-raise", ext: "jpg", from: "free-exercise-db" },
  "Single Leg Squat": { key: "single-leg-squat", ext: "svg", from: "everkinetic" },
  "Skull Crushers": { key: "skull-crushers", ext: "jpg", from: "free-exercise-db" },
  "Smith Machine Bench Press": { key: "smith-machine-bench-press", ext: "svg", from: "everkinetic" },
  "Smith Machine Shrug": { key: "smith-machine-shrug", ext: "svg", from: "everkinetic" },
  "Smith Machine Squat": { key: "smith-machine-squat", ext: "svg", from: "everkinetic" },
  "Snatch": { key: "snatch", ext: "jpg", from: "free-exercise-db" },
  "Snatch Deadlift": { key: "snatch-deadlift", ext: "jpg", from: "free-exercise-db" },
  "Snatch Pull": { key: "snatch-pull", ext: "jpg", from: "free-exercise-db" },
  "Spider Curl": { key: "spider-curl", ext: "svg", from: "everkinetic" },
  "Split Jerk": { key: "split-jerk", ext: "jpg", from: "free-exercise-db" },
  "Split Squat": { key: "split-squat", ext: "jpg", from: "free-exercise-db" },
  "Squat Jump": { key: "squat-jump", ext: "jpg", from: "free-exercise-db" },
  "Standing Calf Raise": { key: "standing-calf-raise", ext: "svg", from: "everkinetic" },
  "Standing Leg Curl": { key: "standing-leg-curl", ext: "svg", from: "everkinetic" },
  "Straight Arm Pulldown": { key: "straight-arm-pulldown", ext: "jpg", from: "free-exercise-db" },
  "Sumo Deadlift": { key: "sumo-deadlift", ext: "jpg", from: "free-exercise-db" },
  "Superman": { key: "superman", ext: "svg", from: "everkinetic" },
  "T Bar Row": { key: "t-bar-row", ext: "svg", from: "everkinetic" },
  "Tate Press": { key: "tate-press", ext: "svg", from: "everkinetic" },
  "Thruster": { key: "thruster", ext: "jpg", from: "free-exercise-db" },
  "Tricep Extension": { key: "tricep-extension", ext: "svg", from: "everkinetic" },
  "Tricep Pushdown": { key: "tricep-pushdown", ext: "svg", from: "everkinetic" },
  "Tricep Rope Pushdown": { key: "tricep-rope-pushdown", ext: "svg", from: "everkinetic" },
  "Upright Row": { key: "upright-row", ext: "svg", from: "everkinetic" },
  "Walking Lunge": { key: "walking-lunge", ext: "svg", from: "everkinetic" },
  "Wide Grip Bench Press": { key: "wide-grip-bench-press", ext: "svg", from: "everkinetic" },
  "Wrist Curl": { key: "wrist-curl", ext: "jpg", from: "free-exercise-db" },
  "Zercher Squat": { key: "zercher-squat", ext: "jpg", from: "free-exercise-db" },
  "Zottman Curl": { key: "zottman-curl", ext: "svg", from: "everkinetic" },
};

/** The two frames for an exercise, or null when we only have the drawn figure. */
export function artFor(name: string): { start: string; end: string; from: ArtSource } | null {
  const entry = EXERCISE_ART[name.trim()];
  if (!entry) return null;
  return {
    start: `/exercise-art/${entry.key}-start.${entry.ext}`,
    end: `/exercise-art/${entry.key}-end.${entry.ext}`,
    from: entry.from,
  };
}
