// =============================================================================
// Link previews — the image every share of this site was missing.
//
// Measured off the export: 43 of 805 pages carried an og:image, and the 43 were
// the admin and app screens nobody links to. Every exercise, recipe, article,
// hub and standards page had none.
//
// The cause is a Next.js sharp edge rather than an oversight. The root layout
// sets `openGraph.images`, and a page that sets `openGraph: { title,
// description, url }` REPLACES the whole object — it does not merge. So every
// page that bothered to write a good social title thereby deleted its own
// image, which is the exact opposite of what writing it was for.
//
// A share with no image is a grey rectangle in WhatsApp, Slack, iMessage,
// Discord and every DM this app would spread through. It is the cheapest
// advertising the site has and it was off.
// =============================================================================

import { SITE } from "./seo";
import { ARTICLES } from "./articles";
import { standardPages } from "./standards-page";

/** What Facebook, Twitter, Slack and iMessage all render at. */
export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;

/**
 * Where a section's image lives. Generated by scripts/build-og-images.mjs into
 * public/og/, so it is a plain static file with no runtime and no edge
 * function — this site is a static export and an on-demand OG route cannot
 * exist here.
 */
export function ogPath(slug: string): string {
  return `/og/${slug}.png`;
}

export interface OgImage {
  url: string;
  width: number;
  height: number;
  alt: string;
}

/**
 * The image descriptor for a page, ALWAYS non-empty.
 *
 * Takes a slug that may not have been generated and falls back to the site
 * default rather than returning nothing: a missing file renders as a broken
 * preview, but a missing `images` key renders as no preview at all, and the
 * second is worse and harder to notice.
 */
export function ogImage(slug: string, alt: string, generated: ReadonlySet<string> = ALL_OG): OgImage[] {
  const use = generated.has(slug) ? slug : "default";
  return [{ url: `${SITE}${ogPath(use)}`, width: OG_WIDTH, height: OG_HEIGHT, alt }];
}

/**
 * Every image the build generates, as slugs.
 *
 * A list rather than a directory read, because pages are rendered before the
 * images exist on a cold build and a filesystem check would silently choose
 * the default for everything. The generator reads this same list, so the two
 * cannot disagree — lib/og.test.ts checks that they do not.
 */
export const OG_SECTIONS = [
  "default", "exercises", "recipes", "guides", "drills", "collections",
  "articles", "standards", "cheapest-protein", "plans",
] as const;

/**
 * Every slug the generator writes, sections and per-page alike.
 *
 * Built from the same sources the generator walks, so adding an article or a
 * lift produces its image AND its reference without a second edit — the class
 * of drift that put 762 pages on a default they never asked for.
 */
export const ALL_OG: ReadonlySet<string> = new Set<string>([
  ...OG_SECTIONS,
  ...ARTICLES.map((a) => `articles-${a.slug}`),
  ...standardPages().map(({ slug }) => `standards-${slug}`),
]);

/**
 * The card itself, as SVG. Rasterised at build.
 *
 * Same visual language as the Instagram cards in lib/drill-card.ts — the gold
 * rule, the ink ground, the wordmark bottom-right — because a link preview and
 * a post are the same brand arriving in the same feed.
 */
export function buildOgCardSvg({ kicker, title, subtitle }: {
  kicker: string;
  title: string;
  subtitle?: string;
}): string {
  const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  // SVG has no text wrapping; the estimate only has to keep text inside 1200px.
  const wrap = (text: string, perLine: number, max: number): string[] => {
    const words = text.split(/\s+/);
    const lines: string[] = [];
    let line = "";
    for (const w of words) {
      if ((line + " " + w).trim().length > perLine && line) { lines.push(line); line = w; }
      else line = (line + " " + w).trim();
      if (lines.length === max) break;
    }
    if (line && lines.length < max) lines.push(line);
    return lines;
  };

  const titleLines = wrap(title, 26, 3);
  const subLines = subtitle ? wrap(subtitle, 58, 2) : [];
  // Centred as a block, so a one-line title and a three-line one both sit right.
  let y = Math.round(OG_HEIGHT / 2) - (titleLines.length - 1) * 34 - (subLines.length ? 30 : 0);

  const out: string[] = [];
  for (const line of titleLines) {
    out.push(`<text x="80" y="${y}" font-family="Arial, Helvetica, sans-serif" font-size="68" font-weight="800" fill="#ffffff">${esc(line)}</text>`);
    y += 82;
  }
  y += 12;
  for (const line of subLines) {
    out.push(`<text x="80" y="${y}" font-family="Arial, Helvetica, sans-serif" font-size="30" fill="#94a3b8">${esc(line)}</text>`);
    y += 42;
  }

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${OG_WIDTH}" height="${OG_HEIGHT}" viewBox="0 0 ${OG_WIDTH} ${OG_HEIGHT}">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="#f6d365"/><stop offset="100%" stop-color="#c9962f"/>
    </linearGradient>
  </defs>
  <rect width="${OG_WIDTH}" height="${OG_HEIGHT}" fill="#0a0a0b"/>
  <rect x="0" y="0" width="${OG_WIDTH}" height="10" fill="url(#g)"/>
  <text x="80" y="110" font-family="Arial, Helvetica, sans-serif" font-size="26" font-weight="700" fill="#e3b53f" letter-spacing="4">${esc(kicker.toUpperCase())}</text>
  ${out.join("\n  ")}
  <text x="80" y="${OG_HEIGHT - 60}" font-family="Arial, Helvetica, sans-serif" font-size="28" font-weight="700" fill="#475569">pocketathlete.com</text>
  <text x="${OG_WIDTH - 80}" y="${OG_HEIGHT - 60}" text-anchor="end" font-family="Arial, Helvetica, sans-serif" font-size="32" font-weight="800" fill="#e3b53f">PocketAthlete</text>
</svg>`;
}
